## 24
print("Este programa mostrara la menor cantidad de billetes de cada valor que se puede entregar")
cant=int(input("Por favor digite la cantidad de dinero: "))
cincuenta=int(cant/50000)
veinte=int(cant/20000)
diez=int(cant/10000)
cinco=int(cant/5000)
dos=int(cant/2000)
mil=int(cant/1000)
cien=int(cant/100000)
print("La menor cantidad de billetes de 100000 que se puede obtener es de", cien)
print("La menor cantidad de billetes de 50000 que se puede obtener es de", cincuenta)
print("La menor cantidad de billetes de 20000 que se puede obtener es de", veinte)
print("La menor cantidad de billetes de 10000 que se puede obtener es de", diez)
print("La menor cantidad de billetes de 5000 que se puede obtener es de", cinco)
print("La menor cantidad de billetes de 2000 que se puede obtener es de", dos)
print("La menor cantidad de billetes de 1000 que se puede obtener es de", mil)